### ISSUE TITLE
ModelCache实例属性cls为null

### ISSUE THREAD

**Issue by dendi6666** [cyjishuang/swagger-mode#1]
我是用的swagger为2.9.2版本。在将项目中的class类及jar包引入项目中启动时会报空指针异常！
异常原因出为ParametersReader类中执行readParameters方法中：此处代码
 Field[] fields = ModelCache.getInstance().getParamClass().getDeclaredFields();
在获取ModelCache实例属为null,在代码中未发现有地方调用ModelCache类中的setParamClass方法。
请问是什么原因?是swagger版本问题吗？
以下为报错日志：
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2214)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4992)
	at springfox.documentation.spring.web.scanners.CachingOperationReader.read(CachingOperationReader.java:57)
	at springfox.documentation.spring.web.scanners.ApiDescriptionReader.read(ApiDescriptionReader.java:70)
	at com.spinfosec.utils.swagger.handle.ApiListingJsonScanner.scan(ApiListingJsonScanner.java:123)
	at springfox.documentation.spring.web.scanners.ApiDocumentationScanner.scan(ApiDocumentationScanner.java:71)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.scanDocumentation(DocumentationPluginsBootstrapper.java:101)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:167)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:880)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.spinfosec.Application.main(Application.java:32)
Caused by: java.lang.NullPointerException
	at com.spinfosec.utils.swagger.handle.ParametersReader.readParameters(ParametersReader.java:70)
	at com.spinfosec.utils.swagger.handle.ParametersReader.apply(ParametersReader.java:57)
	at springfox.documentation.spring.web.plugins.DocumentationPluginsManager.operation(DocumentationPluginsManager.java:120)
	at springfox.documentation.spring.web.readers.operation.ApiOperationReader.read(ApiOperationReader.java:73)
	at springfox.documentation.spring.web.scanners.CachingOperationReader$1.load(CachingOperationReader.java:50)
	at springfox.documentation.spring.web.scanners.CachingOperationReader$1.load(CachingOperationReader.java:48)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	... 25 more

**Comment by baiyangtangliming** [comment]
<context:component-scan base-package="io.github.cyjishuang"/>

**Comment by chy996633** [comment]
我也发现这个问题，扫描到对象也是

**Comment by cyjishuang** [comment]
> 我也发现这个问题，扫描到对象也是

配置有做么？

**Comment by cyjishuang** [comment]
> 我也发现这个问题，扫描到对象也是

createRestApi 的时候要初始化ModelCache的基础类的

**Comment by chy996633** [comment]
哦，我再看下

**Comment by chy996633** [comment]
可以了，谢谢，回复很迅速
```
 public Docket createRestApi() {
        ModelCache.getInstance().setParamClass(GlobalString.class);
        return new Docket(DocumentationType.SWAGGER_2)...
```

**Comment by chy996633** [comment]
另外，我如果只想描述 返回JSONObject参数 怎么定义注解？

**Comment by cyjishuang** [comment]
> 另外，我如果只想描述 返回JSONObject参数 怎么定义注解？

JSONObject参数？直接用swagger官方方式（POJO）就可以了

或者项目一定要返回String，用我文档里的@ApiJsonObject

**Comment by chy996633** [comment]
你的意思是写一个pojo 来描述json是吧。
现在项目的要求是要通过注释来标明返回JSONObject的结构，不另外写pojo


 
---原始邮件---
发件人: "cyjishuang"<notifications@github.com>
发送时间: 2019年7月5日(星期五) 下午2:38
收件人: "cyjishuang/swagger-mode"<swagger-mode@noreply.github.com>;
抄送: "chy996633"<410775541@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [cyjishuang/swagger-mode] ModelCache实例属性cls为null (#1)


 
另外，我如果只想描述 返回JSONObject参数 怎么定义注解？
  
JSONObject参数？直接用swagger官方方式（POJO）就可以了
 
或者项目一定要返回String，用我文档里的@ApiJsonObject

**Comment by cyjishuang** [comment]
那跟着文档写就可以了呀，这个插件就是干这个的，用@ApiJsonObject
